name: Demo ci/cd

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 12 * * *'
jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      
      # Setup Node
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.1.2
      with:
        node-version: 15
      
      # Install dependencies
    - name: Install dependencies
      run: npm install
    
    # Cache node modules
    - name: Cache node modules
      uses: actions/cache@v2
      with:
        # npm cache files are stored in `~/.npm` on Linux/macOS
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

      # Build and gen api document
    - name: Build
      run: npm run build:staging
      
      # Copy build folder to server
    - name: SCP Files
      # You may pin to the exact commit or the version.
      # uses: appleboy/scp-action@b476d5806f2a4c1ed5902a87fa91b0623cac7258
      uses: appleboy/scp-action@master
      with:
        host: 'ec2-54-254-26-105.ap-southeast-1.compute.amazonaws.com'
        username: ${{ secrets.USERNAME }}
        port: ${{ secrets.PORT }}
        key: ${{ secrets.KEY }}
        source: "dist, package.json,ecosystem-staging.json, docker/staging.dockerfile"
        target: "app"
        rm: true
